name: CI
on:
  push:
    tags:
      - 'v**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          FULL_VER=${GITHUB_REF#refs/tags/v}
          MINOR_VER=${FULL_VER%.*}
          MAJOR_VER=${MINOR_VER%.*}
          TAGS="${DOCKER_IMAGE}:${FULL_VER},${DOCKER_IMAGE}:${MINOR_VER},${DOCKER_IMAGE}:${MAJOR_VER},${DOCKER_IMAGE}:latest"
          echo ::set-output name=tags::${TAGS}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.prep.outputs.tags }}

# vim: set ts=2 sw=2 expandtab:
